### ISSUE TITLE
Right-click in cell gives AttributeError

### ISSUE THREAD

**Issue by dschreij** [smathot/python-qdatamatrix#1]
**Platform** OSX El-Capitan
**Python** 2.7.12
**PyQt** 5.6
**Qt** 5.6.1

Right clicking in a cell results in the following stacktrace:

``` python
Traceback (most recent call last):
  File "../smathot/python-qdatamatrix/qdatamatrix/_qspreadsheet.py", line 107, in contextMenuEvent
    QContextMenu(self).exec_(e.globalPos())
  File "../smathot/python-qdatamatrix/qdatamatrix/_qcontextmenu.py", line 111, in __init__
    self.addAction(QCutAction(self))
  File "../smathot/python-qdatamatrix/qdatamatrix/_qcontextmenu.py", line 60, in __init__
    QContextAction.__init__(self, u'edit-cut', _(u'Cut'), menu, u'Ctrl+X')
  File "../smathot/python-qdatamatrix/qdatamatrix/translate.py", line 29, in _
    encoding=QCoreApplication.UnicodeUTF8)
AttributeError: type object 'QCoreApplication' has no attribute 'UnicodeUTF8'
```

**Comment by smathot** [comment]
Fixed in #1.
